### PR TITLE
 Makes Tracer.currentSpanCustomizer() lazy 

### LINKED ISSUE #920: brave.flush annotation reported for already finished span
## Problem
Brave Version: 5.6.0

I am encountering unexpected behavior when using Tracer.currentSpan() to get a span that has previously been finished. It appears that calling currentSpan() restarts the span to a degree in that the TraceContext is re-registered with PendingSpans. This in turn causes a brave.flush annotation to be reported when that TraceContext gets GC'd even though in reality the span has already been finished.
Untitled Diagram(2)

This could probably be avoided by calling abandon() on the Span that is returned from currentSpan(), but in our case sometimes this code lives in libraries that are not aware whether or not the current span needs to be abandoned() (it was finished previously) or if it will be finished later.

This is also causing odd behavior in zipkin-ui (not lens) such as spans going missing presumably because it doesn't expect multiple spans with the same spanId that aren't shared spans. (For example I found one span had three documents in elasticsearch: a client span, a servier span, and another span with the brave.flush annotation)

## Proposed Fix
I wonder if instead of removing PendingSpan entries from the HashMap when PendingSpans.remove() is invoked, these entries could be marked as finished somehow. In this manner PendingSpans will not forget about a TraceContext until it has been GC'd meaning that the context can never be registered with pending spans more than once.

If this approach is pursued, special care will need to be taken when dealing with multiple Tracer instances, as each Tracer has it's own instance of PendingSpans that needs to remain in sync.

I have attached a sample project with unit tests for both a single tracer and multiple tracer test that exhibits this behavior.
[bugjar.zip](https://github.com/apache/incubator-zipkin-brave/files/3267116/bugjar.zip)

### PR DESCRIPTION
**Pull request by adriancole**
@lambcode noticed that calling `Tracer.currentSpan()` without using the
result can lead to orphaned spans. The simplest way to prevent this is
to defer overhead until data is added with the result.

Fixes #920

Added benchmarks..

before

```
TracerBenchmarks.currentSpan:currentSpan·p0.999                          sample             8.560             us/op
TracerBenchmarks.currentSpan:·gc.alloc.rate.norm                         sample      15    88.012 ±   0.005    B/op
TracerBenchmarks.currentSpan_tag:currentSpan_tag·p0.999                  sample            20.256             us/op
TracerBenchmarks.currentSpan_tag:·gc.alloc.rate.norm                     sample      15    88.065 ±   0.004    B/op
TracerBenchmarks.currentSpan_unsampled:currentSpan_unsampled·p0.999      sample             4.995             us/op
TracerBenchmarks.currentSpan_unsampled:·gc.alloc.rate.norm               sample      15    24.005 ±   0.001    B/op
```

after

```
TracerBenchmarks.currentSpan:currentSpan·p0.999                          sample              7.974             us/op
TracerBenchmarks.currentSpan:·gc.alloc.rate.norm                         sample      15     24.015 ±   0.008    B/op
TracerBenchmarks.currentSpan_tag:currentSpan_tag·p0.999                  sample             10.192             us/op
TracerBenchmarks.currentSpan_tag:·gc.alloc.rate.norm                     sample      15     72.050 ±  12.511    B/op
TracerBenchmarks.currentSpan_unsampled:currentSpan_unsampled·p0.999      sample              4.198             us/op
TracerBenchmarks.currentSpan_unsampled:·gc.alloc.rate.norm               sample      15     24.009 ±   0.007    B/op
```

### CODE REVIEW

**Comment by adriancole** [comment]
I built this over the commits in #921 to ensure tests would pass considering the use case described

**Comment by adriancole** [comment]
ps the use cases for calling tracer.currentSpan and not using the result are one of..
* checking null from `tracer.currentSpan()` as a signal for "is current"
* defensively doing some parsing based on whether or not `Span.isNoop()`

just guessing.. I think usually it would be a bug to call `Tracer.currentSpan()` and drop the result.

File: brave/src/main/java/brave/LazySpan.java [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package brave;
+
+import brave.propagation.TraceContext;
+
+/** This wraps the public api and guards access to a mutable span. */
```
Comment (anuraaga) [inline brave/src/main/java/brave/LazySpan.java]: Don't think this "guards" from someone - how about explicitly saying "ensuring a `Span` is only constructed on first API method call"?

File: brave/src/main/java/brave/LazySpan.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+    } else if (o instanceof RealSpan) {
+      return context.equals(((RealSpan) o).context);
+    }
+    return false;
+  }
+
+  Span span() {
+    Span result = delegate;
+    if (result != null) return result;
+    return delegate = tracer.toSpan(context);
```
Comment (anuraaga) [inline brave/src/main/java/brave/LazySpan.java]: I'm not sure what the thread-safety guarantees of `Span` are, but I think normally we'd want to double-lock here to prevent multiple spans being created if accessing from different threads at the same time.

```java
if (result != null) return result;
synchronized {
  result = delegate;
  if (result != null) return result;
  return delegate = tracer.toSpan(context);
}
```

Comment (anuraaga) [reply brave/src/main/java/brave/LazySpan.java]: `abandon` and `flush` would need similar too if the thread-safety matters.

File: brave/src/main/java/brave/LazySpan.java [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+    span().flush();
+  }
+
+  @Override public String toString() {
+    return "LazySpan(" + context + ")";
+  }
+
+  @Override public boolean equals(Object o) {
+    if (o == this) return true;
+    if (o instanceof LazySpan) {
```
Comment (anuraaga) [inline brave/src/main/java/brave/LazySpan.java]: How about a package-private method that returns the context?

Comment (adriancole) [reply brave/src/main/java/brave/LazySpan.java]: I don't know if there are any other callers that would use them... usually we don't add methods for single call sites.

File: brave/src/main/java/brave/LazySpan.java (hunk 2 above)
Comment (adriancole) [reply brave/src/main/java/brave/LazySpan.java]: I forgot a comment I guess. Multiple copies of Span are not a problem apart from overhead. It is probably not worth optimizing the code as that would hint there is a problem. I will add a comment, thanks!

File: brave/src/main/java/brave/LazySpan.java (hunk 1 above)
Comment (adriancole) [reply brave/src/main/java/brave/LazySpan.java]: this doc was meant for another type :) will fix!

File: brave/src/main/java/brave/LazySpan.java (hunk 2 above)
Comment (adriancole) [reply brave/src/main/java/brave/LazySpan.java]: hope the comments help

**Comment by adriancole** [comment]
I caused a bug https://github.com/apache/incubator-zipkin-brave/pull/927
